const cvLocalizations = {
    en: {
      contactInformation: "Contact Information",
      email: "Email",
      phone: "Phone",
      location: "Location",
      summary: "About Me",
      skills: "Skills",
      workExperience: "Work Experience",
      education: "Education",
      date: "Date",
      description: "Description",
      availability: "Availability",
      hourlyRate: "Hourly Rate",
      languages: "Languages",
      portfolio: "Portfolio",
      testimonials: "Testimonials",
      certifications: "Certifications",
      title: "Title",
      company: "Company",
    },
    es: {
      contactInformation: "Información de Contacto",
      email: "Correo Electrónico",
      phone: "Teléfono",
      location: "Ubicación",
      summary: "Acerca de mí",
      skills: "Habilidades",
      workExperience: "Experiencia Laboral",
      education: "Educación",
      date: "Fecha",
      description: "Descripción",
      availability: "Disponibilidad",
      hourlyRate: "Tarifa Horaria",
      languages: "Idiomas",
      portfolio: "Portafolio",
      testimonials: "Testimonios",
      certifications: "Certificaciones",
      title: "Título",
      company: "Empresa",
    },
    fr: {
      contactInformation: "Informations de contact",
      email: "Email",
      phone: "Téléphone",
      location: "Lieu",
      summary: "A Propos de Moi",
      skills: "Compétences",
      workExperience: "Expérience professionnelle",
      education: "Formation",
      date: "Date",
      description: "Description",
      availability: "Disponibilité",
      hourlyRate: "Taux horaire",
      languages: "Langues",
      portfolio: "Portfolio",
      testimonials: "Témoignages",
      certifications: "Certifications",
      title: "Titre",
      company: "Entreprise",
    },
    ru: {
      contactInformation: "Контактная информация",
      email: "Электронная почта",
      phone: "Телефон",
      location: "Местоположение",
      summary: "Обо мне",
      skills: "Навыки",
      workExperience: "Опыт работы",
      education: "Образование",
      date: "Дата",
      description: "Описание",
      availability: "Доступность",
      hourlyRate: "Ставка за час",
      languages: "Языки",
      portfolio: "Портфолио",
      testimonials: "Отзывы",
      certifications: "Сертификаты",
      title: "Должность",
      company: "Компания",
    }
  };